version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_name_backend
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py loaddata taskManager/fixtures/* && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
volumes:
  data:
