# Generated by Django 5.1.2 on 2024-10-21 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_auto_20230915_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 36, 4, 793309, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 36, 4, 793768, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
    ]
