# Generated by Django 5.1.2 on 2024-10-21 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_alter_project_due_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 49, 20, 618367, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 2, 49, 20, 618818, tzinfo=datetime.timezone.utc), verbose_name='date due'),
        ),
    ]
